version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: achievements_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
